name: Full Build

permissions:
  contents: write

on:
  push:
    branches: [ C# ]
    tags: [ '*' ]

jobs:
  build-cpp:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - { name: linux, os: ubuntu-latest, arch: x86_64 }
          - { name: macosx, os: macos-13, arch: x86_64 }
          - { name: windows, os: windows-latest, arch: x64 }
        kind: [shared]
        mode: [releasedbg]

    runs-on: ${{ matrix.runner.os }}

    steps:
      - name: Get current date as package key
        id: cache_key
        run: echo "key=$(date +'%W')_${{ matrix.runner.os }}_${{ matrix.runner.arch }}_${{ matrix.kind }}_${{ matrix.mode }}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Set vs_runtime string
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            echo "VS_RUNTIME_STRING=--runtimes=MD" >> $GITHUB_ENV
          else
            echo "VS_RUNTIME_STRING= " >> $GITHUB_ENV
          fi
        shell: bash

      - name: Set OUTPUT_FILE variable
        run: echo "OUTPUT_FILE=${{ matrix.runner.name }}.zip" >> $GITHUB_ENV
        shell: bash

      - name: Set xmake env
        run: echo "XMAKE_GLOBALDIR=${{ runner.workspace }}/xmake-global" >> $GITHUB_ENV
        shell: bash

      - name: Checkout C++
        uses: actions/checkout@v4
        with:
          ref: C++
          path: Cpp

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1.2.2
        with:
          #xmake-version: branch@dev
          xmake-version: latest
          actions-cache-folder: .xmake-cache-W${{ steps.cache_key.outputs.key }}

      - name: Update xmake repository
        run: xmake repo --update -vD
        shell: bash
        working-directory: Cpp

      - name: Install nasm
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get install nasm
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew install nasm
          else
            echo "Done"
          fi
        shell: bash

      - name: Configure xmake and install dependencies
        run: xmake config -vD --plat=${{ matrix.runner.name }} --arch=${{ matrix.runner.arch }} --mode=${{ matrix.mode }} --kind=${{ matrix.kind }} ${{ env.VS_RUNTIME_STRING }} --yes --policies=package.precompiled:n
        shell: bash
        working-directory: Cpp

      - name: Build all targets
        run: xmake build -vD -a
        shell: bash
        working-directory: Cpp

      ## We can't do --group=TESTS because every test has its own output
      #- name: Run tests
      #  run: xmake run -vD --group=TESTS
      #  shell: bash
      #  working-directory: Cpp

      - name: Install
        run: xmake install -vDo _dest/ --group=LIBS
        shell: bash
        working-directory: Cpp

      - name: Prepare Cpp artifacts for release
        uses: christopherhx/gitea-upload-artifact@v4
        with:
          name: Cpp-${{ matrix.runner.name }}
          path: Cpp/_dest/*

  build-cs:
    runs-on: ubuntu-latest

    needs:
      - build-cpp

    steps:
      - name: Get tag number from tag string
        id: tag_number
        if: ${{ startsWith( github.ref, 'refs/tags/' ) }}
        run: |
          orig_tag="${{ github.ref_name }}"
          echo "tag_number=${orig_tag/v/}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Download Artifacts
        uses: christopherhx/gitea-download-artifact@v4
        with:
          path: artifacts

      - name: Checkout Cs
        uses: actions/checkout@v4
        with:
          ref: C#
          path: Cs

      - name: Setup MAPI
        uses: BadMagic100/setup-hk@v2
        with:
          apiPath: HkRefs
          dependencyFilePath: Cs/ModDependencies.txt

      - name: Install dependencies Cs
        run: dotnet restore
        shell: bash
        working-directory: Cs

      - name: Build Cs
        run: dotnet build -c Release /p:AssemblyVersion=${{ steps.tag_number.outputs.tag_number }}
        shell: bash
        working-directory: Cs

      - name: Prepare Cs artifacts for release
        uses: christopherhx/gitea-upload-artifact@v4
        with:
          name: Publish-Cs
          path: Cs/bin/Publish

  release:
    if: ${{ startsWith( github.ref, 'refs/tags/' ) }}
    needs:
      - build-cs

    runs-on: ubuntu-latest

    steps:
      - name: Download Artifacts
        uses: christopherhx/gitea-download-artifact@v4
        with:
          path: artifacts

      - name: Get build details
        id: details
        run: |
          sha="$(sed '4q;d' artifacts/Publish-Cs/VideoEncoder/SHA.txt)"
          ver="${{ github.ref_name }}"
          echo "archiveHash=$sha" >> $GITHUB_OUTPUT
          echo "buildVersion=$ver" >> $GITHUB_OUTPUT
        shell: bash

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          generate_release_notes: true
          fail_on_unmatched_files: true
          tag_name: ${{ steps.details.outputs.buildVersion }}
          body: |
            SHA256 of VideoEncoder.zip: ${{ steps.details.outputs.archiveHash }}  
            Attachments:  
            - VideoEncoder.zip
              - to be used for the ModInstaller
            - VideoEncoder.dll
              - the mod, also inside VideoEncoder.zip
          files: |
            artifacts/Publish-Cs/VideoEncoder/VideoEncoder.zip
            artifacts/Publish-Cs/VideoEncoder/VideoEncoder.dll
